language: objective-c
osx_image: xcode9.0
env:
- DESTINATION="OS=11.0,name=iPhone 8" SCHEME="ImageRow" SDK=iphonesimulator11.0

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage update --platform iOS
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -project ImageRow.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -project ImageRow.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
